# .platform/app.yaml
name: php-backend
type: 'php:8.2'
disk: 512

source:
  root: backend

build:
  flavor: composer

runtime:
  extensions:
    - sodium

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]
      passthru: "/index.php"
      scripts: true
      allow: true

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader

dependencies:
  php:
    composer/composer: "^2"

relationships:
  # Doit matcher le service défini dans .platform/services.yaml
  database: "mysql:mysql"

variables:
  env:
    # Reconstruit DATABASE_URL en TCP (évite le socket UNIX → “No such file or directory”)
    DATABASE_URL: "mysql://${database_USERNAME}:${database_PASSWORD}@tcp(${database_HOST}:${database_PORT})/${database_PATH}?serverVersion=11.0"
