# .platform/app.yaml
name: php-backend
type: 'php:8.2'
disk: 512

source:
  root: backend     # Permet d’installer les dépendances dans backend/

build:
  flavor: composer

runtime:
  extensions:
    - sodium

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]
      passthru: "/index.php"
      scripts: true
      allow: true

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    # Installe les dépendances sans lancer les auto-scripts Symfony
    composer install \
      --no-dev \
      --prefer-dist \
      --no-progress \
      --no-interaction \
      --optimize-autoloader \
      --no-scripts

dependencies:
  php:
    composer/composer: "^2"


variables:
  env:
    # Utilise la vraie variable ${database_DATABASE} pour le nom de la base
    DATABASE_URL: "mysql://${database_USERNAME}:${database_PASSWORD}@tcp(${database_HOST}:${database_PORT})/${database_DATABASE}?serverVersion=11.0"
