# .platform.app.yaml
name: php-backend
type: 'php:8.2'
disk: 512

source:
  root: backend

build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]
      passthru: "/index.php"
      scripts: true
      allow: true

hooks:
  build: |
    set -e
    composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader --no-scripts

relationships:
  database: "mysql:mysql"  # <— on prend le service 'mysql' et on l’appelle 'database'

variables:
  env:
    DATABASE_URL: "mysql://${database_USERNAME}:${database_PASSWORD}@tcp(${database_HOST}:${database_PORT})/${database_PATH}?serverVersion=11.0"
