name: php-backend
type: 'php:8.2'

disk: 512

runtime:
  extensions:
    - sodium

web:
  locations:
    "/":
      root: "public"
      index:
        - index.php
      passthru: "/index.php"
      scripts: true
      allow: true

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader

dependencies:
  php:
    composer/composer: "^2"

relationships:
  mysql: 'mysql:mysql'
