version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: styx-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: styxdb
      MYSQL_USER: styx
      MYSQL_PASSWORD: styxpass
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
