name: app
type: php:8.2
disk: 2048

web:
  locations:
    "/":
      root: "backend/public"
      index: "index.php"
      scripts: true

mounts:
  "/backend/var": { source: local, source_path: "var" }

dependencies:
  php:
    - ext-pdo
    - ext-mysqli

hooks:
  build: |
    set -e
    cd backend
    composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

relationships:
  database: "db:mysql"

crons:
  symfony-cron:
    spec: "*/10 * * * *"
    cmd: "cd backend && php bin/console messenger:consume async -vv"
