name: php-backend
type: 'php:8.2'
disk: 512

source:
  root: backend

build:
  flavor: composer

runtime:
  extensions:
    - sodium

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]
      passthru: "/index.php"
      scripts: true
      allow: true

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    # pas de scripts PHP à ce stade
    composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader --no-scripts

dependencies:
  php:
    composer/composer: "^2"

relationships:
  # on lie le service mysql (défini ci-dessous) sous l’alias « database »
  database: "mysql:mysql"

variables:
  env:
    # rebuild en TCP pour Doctrine
    DATABASE_URL: "mysql://${database_USERNAME}:${database_PASSWORD}@tcp(${database_HOST}:${database_PORT})/${database_PATH}?serverVersion=11.0"
