# .platform/app.yaml
name: php-backend
type: 'php:8.2'
disk: 512

source:
  root: backend

build:
  flavor: composer

runtime:
  extensions:
    - sodium

web:
  locations:
    "/":
      root: "public"
      index: [ "index.php" ]
      passthru: "/index.php"
      scripts: true
      allow: true

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    echo "→ DEBUG ENV VARS →"
    echo "DATABASE_HOST     = $DATABASE_HOST"
    echo "DATABASE_PORT     = $DATABASE_PORT"
    echo "DATABASE_USERNAME = $DATABASE_USERNAME"
    echo "DATABASE_PASSWORD = $DATABASE_PASSWORD"
    echo "DATABASE_DATABASE = $DATABASE_DATABASE"
    echo "→ Constructed DSN →"
    echo "DATABASE_URL = $DATABASE_URL"
    composer install --no-dev --prefer-dist --no-progress \
      --no-interaction --optimize-autoloader --no-scripts

dependencies:
  php:
    composer/composer: "^2"

relationships:
  database: "mysql:mysql"

variables:
  env:
    DATABASE_URL: "mysql://${database_USERNAME}:${database_PASSWORD}@tcp(${database_HOST}:${database_PORT})/${database_DATABASE}?serverVersion=11.0"
