# .platform/app.yaml  (placez ce fichier dans .platform/app.yaml et supprimez l’ancien .platform.app.yaml)
name: php-backend
type: 'php:8.2'
disk: 512

source:
  root: backend

build:
  flavor: composer

runtime:
  extensions:
    - sodium

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]
      passthru: "/index.php"
      scripts: true
      allow: true

mounts:
  "/var": "shared:files"

hooks:
  build: |
    set -e
    # Installe sans lancer les auto-scripts (cache:clear etc.)
    composer install \
      --no-dev \
      --prefer-dist \
      --no-progress \
      --no-interaction \
      --optimize-autoloader \
      --no-scripts
    # Facultatif : précuisine le cache sans DB
    php backend/bin/console cache:warmup --env=prod --no-debug || true

dependencies:
  php:
    composer/composer: "^2"

relationships:
  database: "mysql:mysql"

variables:
  env:
    # URL de connexion TCP à MySQL (évite le socket UNIX)
    DATABASE_URL: "mysql://${database_USERNAME}:${database_PASSWORD}@tcp(${database_HOST}:${database_PORT})/${database_PATH}?serverVersion=11.0"
